name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: slef-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g @nestjs/cli  # Install NestJS CLI globally
    - run: npm install  # Install project dependencies
    - run: npm install dotenv
    - run: npm install --save-dev @types/dotenv
    - run: |
        touch .env
        echo "${{ secrets.LEO_KNWOLEDGE_SECRET }}" > .env
    - run: npm run build --if-present
    
